<?php
require_once('../Barstool.php');


$bs = new Barstool(
    array(
        'adaptor'=>'sqlite'
    )
);

/*
    delete everything
*/
$bs->nuke();

/*
    make a new object to store
*/
$obj = new stdClass;
$obj->foo = 'bar';
$obj->x = '2000';
$obj->key = 'foobarthing'; // the key property is a custom id. Otherwise a UUID is generated by barstool

/*
    store it and delete it
*/
$bs->save($obj);
unset($obj);

/*
    retrieve it
*/
$obj = $bs->get('foobarthing');

var_dump($obj);

$bs->remove('foobarthing');

?>